services:
  app:
    build:
      context: .
    ports:
      - "3000:3000" # Map host port 3000 to container port 3000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    command: pnpm run start:dev

  redis:
    image: redis:alpine
    ports:
      - "6379:6379" #
    volumes:
      - redis-data:/data

volumes:
  redis-data:
